### ISSUE TITLE
ANSI Escapes.

### ISSUE THREAD

**Issue by ateesdalejr** [Olimooseman/HackIt#1]
@Olimooseman It seems that on Windows in command prompt it looks like this even while colorama is installed:
![glitch3](https://cloud.githubusercontent.com/assets/16790483/20642963/bbc74b5a-b3d1-11e6-8a4a-8b3c81686f8c.PNG)

**Comment by ateesdalejr** [comment]
Now that I think about it colorama isn't supported by py3...

**Comment by ateesdalejr** [comment]
Unless you are running a specific version.

**Comment by olifog** [comment]
Oooh
Actually, I think it's Mac-only
Soz about that :/

**Comment by ateesdalejr** [comment]
@Olimooseman I used to use this module on windows though... And it worked.

**Comment by olifog** [comment]
Maybe I'm implementing it incorrectly with py3?

**Comment by ateesdalejr** [comment]
I don't know, I'm working on a PR with a way to exclude the module if the system is Windows

**Comment by ateesdalejr** [comment]
@Olimooseman Okay I've created a pull request. Test it please. I think it will work on windows. I wanna see if it works on mac as well.

**Comment by olifog** [comment]
kk

**Comment by ateesdalejr** [comment]
Thanks.

**Comment by olifog** [comment]
Just tested it! It works fine :D

**Comment by ateesdalejr** [comment]
Great!

**Comment by olifog** [comment]
Yay! :3

**Comment by ateesdalejr** [comment]
@Olimooseman  Oops... I forgot to add a self.BLUE attribute to the DummyFore class. :/
