### ISSUE TITLE
Missing self.BLUE attr in DummyFore

### ISSUE THREAD

**Issue by ateesdalejr** [Olimooseman/HackIt#3]
Forgot to add this. :(

**Comment by ateesdalejr** [comment]
@Olimooseman it causes it to crash for me.

**Comment by olifog** [comment]
:/
That ain't good

**Comment by ateesdalejr** [comment]
You would simply need to add this line to the DummyFore class `self.BLUE=''`

**Comment by olifog** [comment]
Done! :)

**Comment by ateesdalejr** [comment]
Thanks!

**Comment by olifog** [comment]
Tell me what you think of the game XD

**Comment by ateesdalejr** [comment]
I will in a second.

**Comment by ateesdalejr** [comment]
@Olimooseman  Yay!
![glitchfix3](https://cloud.githubusercontent.com/assets/16790483/20643708/4187a2f4-b3d6-11e6-9423-7c28ace14487.PNG)

**Comment by olifog** [comment]
Woohoo! 👍

**Comment by ateesdalejr** [comment]
@Olimooseman It's pretty fun so far. Very cryptic though. 👍

**Comment by olifog** [comment]
Haha sorry about that... the developer was too lazy to add a complete tutorial...

**Comment by ateesdalejr** [comment]
Makes the game challenging though!

**Comment by ateesdalejr** [comment]
Well I'm off to find more glitches for ya. So going to close this issue for now.

**Comment by olifog** [comment]
kk :3
