### ISSUE TITLE
help caused a crash.

### ISSUE THREAD

**Issue by ateesdalejr** [Olimooseman/HackIt#4]
Asking it to `help <command>` causes it to crash.

**Comment by olifog** [comment]
uh oh
Wait lemme check that

**Comment by ateesdalejr** [comment]
Replace the `<command>` with any command.

**Comment by olifog** [comment]
I was planning on adding a command help menu (how to use the specified command) but I wanted it to be more of a learn-as-you-play game.

**Comment by ateesdalejr** [comment]
Yeah, how might I disconnect from the server? It tells me `disconnect: Is not a valid command.`

**Comment by olifog** [comment]
Just connect to another server

**Comment by ateesdalejr** [comment]
Oh... Didn't know my home shell was a server.

**Comment by olifog** [comment]
It's not possible to not be connected to any server... Maybe I should add the command "disconnect" to connect you to home.server

**Comment by olifog** [comment]
Yeah, sorry 'bout that XD

**Comment by ateesdalejr** [comment]
It is apparently. I'm connected to tut.server

**Comment by ateesdalejr** [comment]
You may want to add `bye` instead. As it's more commonly used.

**Comment by olifog** [comment]
Haha alright

**Comment by ateesdalejr** [comment]
Is the mac address in there real?

**Comment by olifog** [comment]
Nah, I got it from a random generator online

**Comment by olifog** [comment]
gtg btw
bai :3
