### ISSUE TITLE
hackit.server doesn't exist.

### ISSUE THREAD

**Issue by ateesdalejr** [Olimooseman/HackIt#5]
It seems the game allows me to connect to any server no matter if it exists or not. `hackit.server` seems to be unimplemented. 🤒

**Comment by olifog** [comment]
That's a feature, not a bug! There only files in certain servers, though :)
And the game basically stops rn at hackit.server... I'll continue making servers/missions/storyline in the next few updates

**Comment by ateesdalejr** [comment]
Ah.
